import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
  UpdateDateColumn,
} from 'typeorm';
import { User } from './user.entity';

/**
 * One row per login (or registration). The row keeps only a keyed hash of the
 * session's current refresh token; each refresh replaces that hash, so older
 * tokens of the same session stop matching.
 */
@Entity({ name: 'refresh_sessions' })
@Index('IDX_refresh_sessions_user_id', ['userId'])
export class RefreshSession {
  /** Generated by the API because the refresh token embeds it (`sid`). */
  @PrimaryColumn({
    type: 'uuid',
    primaryKeyConstraintName: 'PK_refresh_sessions_id',
  })
  id: string;

  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, { nullable: false, onDelete: 'CASCADE' })
  @JoinColumn({
    name: 'user_id',
    foreignKeyConstraintName: 'FK_refresh_sessions_user_id',
  })
  user: User;

  /** HMAC-SHA-256 (hex) of the current refresh token. Never the token itself. */
  @Column({ name: 'token_hash', type: 'char', length: 64, select: false })
  tokenHash: string;

  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt: Date;

  @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true })
  revokedAt: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;
}
