import { ApiProperty } from '@nestjs/swagger';
import {
  IsEnum,
  IsISO8601,
  IsUUID,
  Matches,
  ValidateIf,
} from 'class-validator';
import { MealAlternative } from '../../recommendations/enums/meal-alternative.enum';
import { AnalyticsEventType } from '../enums/analytics-event-type.enum';
import { ClientPlatform } from '../enums/client-platform.enum';

/**
 * Body of `POST analytics/events`. Deliberately has no explanation, location, token or
 * free-text field: the global whitelist rejects anything else a client tries to send.
 */
export class CreateAnalyticsEventDto {
  @ApiProperty({
    example: '1de89c60-714d-4d12-ae34-946cedd79f9a',
    description:
      'UUID generated by the client. Re-sending the same value (a retry) is accepted but stored only once.',
  })
  @IsUUID()
  clientEventId: string;

  @ApiProperty({
    example: '3f0c2a5e-8f7b-4c4e-9d61-2b1f0a9c7e11',
    description:
      '`recommendationId` returned by `POST meal-decisions/compare`.',
  })
  @IsUUID()
  recommendationId: string;

  @ApiProperty({ enum: AnalyticsEventType })
  @IsEnum(AnalyticsEventType)
  eventType: AnalyticsEventType;

  @ApiProperty({
    enum: MealAlternative,
    nullable: true,
    description:
      'Required for RECOMMENDATION_SELECTED; must be null or omitted for RECOMMENDATION_IMPRESSION.',
  })
  @ValidateIf(
    (dto: CreateAnalyticsEventDto) =>
      dto.eventType === AnalyticsEventType.RECOMMENDATION_SELECTED,
  )
  @IsEnum(MealAlternative, {
    message:
      'selectedAlternative must be one of COOK, WALK, ORDER for RECOMMENDATION_SELECTED',
  })
  selectedAlternative?: MealAlternative | null;

  @ApiProperty({ enum: ClientPlatform })
  @IsEnum(ClientPlatform)
  platform: ClientPlatform;

  @ApiProperty({
    example: '2026-09-21T17:30:05Z',
    description: 'ISO-8601 UTC instant. A Z suffix is required.',
  })
  @IsISO8601({ strict: true, strictSeparator: true })
  @Matches(/Z$/, {
    message: 'occurredAt must be an ISO-8601 UTC instant ending in Z',
  })
  occurredAt: string;
}
