import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { MealAlternative } from '../../recommendations/enums/meal-alternative.enum';
import { RecommendationRun } from '../../recommendations/entities/recommendation-run.entity';
import { User } from '../../users/entities/user.entity';
import { AnalyticsEventType } from '../enums/analytics-event-type.enum';
import { ClientPlatform } from '../enums/client-platform.enum';

/**
 * One impression or selection of a BQ5 recommendation, sent by a mobile client.
 * Holds no coordinates, tokens or passwords. The explanation category is NOT stored here:
 * BQ8 reads it from the recommendation run, so clients cannot decide or tamper with it.
 */
@Entity({ name: 'analytics_events' })
@Index('UQ_analytics_events_client_event_id', ['clientEventId'], {
  unique: true,
})
@Index('IDX_analytics_events_recommendation_id', ['recommendationId'])
@Index('IDX_analytics_events_occurred_at', ['occurredAt'])
export class AnalyticsEvent {
  @PrimaryGeneratedColumn('uuid', {
    primaryKeyConstraintName: 'PK_analytics_events_id',
  })
  id: string;

  /** Generated by the client; makes retries idempotent. */
  @Column({ name: 'client_event_id', type: 'uuid' })
  clientEventId: string;

  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, { nullable: false, onDelete: 'CASCADE' })
  @JoinColumn({
    name: 'user_id',
    foreignKeyConstraintName: 'FK_analytics_events_user_id',
  })
  user: User;

  @Column({ name: 'recommendation_id', type: 'uuid' })
  recommendationId: string;

  @ManyToOne(() => RecommendationRun, { nullable: false, onDelete: 'CASCADE' })
  @JoinColumn({
    name: 'recommendation_id',
    foreignKeyConstraintName: 'FK_analytics_events_recommendation_id',
  })
  recommendation: RecommendationRun;

  @Column({
    name: 'event_type',
    type: 'enum',
    enum: AnalyticsEventType,
    enumName: 'analytics_event_type',
  })
  eventType: AnalyticsEventType;

  /** Required for RECOMMENDATION_SELECTED, null for RECOMMENDATION_IMPRESSION. */
  @Column({
    name: 'selected_alternative',
    type: 'enum',
    enum: MealAlternative,
    enumName: 'meal_alternative',
    nullable: true,
  })
  selectedAlternative: MealAlternative | null;

  @Column({
    name: 'platform',
    type: 'enum',
    enum: ClientPlatform,
    enumName: 'client_platform',
  })
  platform: ClientPlatform;

  /** When the event happened on the device (UTC). */
  @Column({ name: 'occurred_at', type: 'timestamptz' })
  occurredAt: Date;

  /** When the backend stored it. */
  @CreateDateColumn({ name: 'received_at', type: 'timestamptz' })
  receivedAt: Date;
}
